// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebMultiempresa.Infrastructure.Persistence;

#nullable disable

namespace WebMultiempresa.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260522122001_PedidosCamposOpcionales")]
    partial class PedidosCamposOpcionales
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebMultiempresa.Domain.Entities.ActorEstadoLog", b =>
                {
                    b.Property<long>("ActorEstadoLogID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ActorEstadoLogID"));

                    b.Property<int>("ActorID")
                        .HasColumnType("int");

                    b.Property<int>("EmpresaID")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaEvento")
                        .HasColumnType("datetime2");

                    b.Property<string>("TipoEvento")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("TiposActoresID")
                        .HasColumnType("int");

                    b.HasKey("ActorEstadoLogID");

                    b.HasIndex("TiposActoresID", "EmpresaID", "TipoEvento", "FechaEvento");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("TiposActoresID", "EmpresaID", "TipoEvento", "FechaEvento"), new[] { "ActorID" });

                    b.ToTable("ActorEstadoLog", (string)null);
                });

            modelBuilder.Entity("WebMultiempresa.Domain.Entities.AltaClientePendiente", b =>
                {
                    b.Property<long>("AltaClientesPendientesID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AltaClientesPendientesID"));

                    b.Property<int?>("ClientesID")
                        .HasColumnType("int");

                    b.Property<string>("CodigoPostal")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("DireccionEnvio")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Documento")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("EmpresaID")
                        .HasColumnType("int");

                    b.Property<string>("ErrorDetalle")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<byte>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)0);

                    b.Property<DateTime?>("FechaConfirmacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaProcesamiento")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaSolicitud")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<decimal?>("Latitud")
                        .HasColumnType("decimal(18,10)");

                    b.Property<string>("Localidad")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("Longitud")
                        .HasColumnType("decimal(18,10)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Password")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Provincia")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TelefonoNormalizado")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<byte?>("TipoDocumento")
                        .HasColumnType("tinyint");

                    b.Property<byte>("TipoUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)1);

                    b.HasKey("AltaClientesPendientesID");

                    b.HasIndex("TelefonoNormalizado");

                    b.HasIndex("EmpresaID", "Estado");

                    b.ToTable("AltaClientesPendientes", (string)null);
                });

            modelBuilder.Entity("WebMultiempresa.Domain.Entities.Aplicacion", b =>
                {
                    b.Property<int>("AplicacionesID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AplicacionesID"));

                    b.Property<bool>("Baja")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("AplicacionesID");

                    b.ToTable("Aplicaciones", (string)null);
                });

            modelBuilder.Entity("WebMultiempresa.Domain.Entities.Cliente", b =>
                {
                    b.Property<int>("ClientesID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClientesID"));

                    b.Property<bool>("Baja")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("ClaveHash")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CodigoPostal")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("ConsumidorFinal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Cuit")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("DiaDeVenta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Direccion")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Dni")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("EmpresaID")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<decimal?>("Latitud")
                        .HasColumnType("decimal(18,10)");

                    b.Property<int>("ListaDePrecioID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Localidad")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal?>("Longitud")
                        .HasColumnType("decimal(18,10)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<decimal>("PorcentajePercepcionIB")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(5,2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("Provincia")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TipoClienteID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("ClientesID");

                    b.HasIndex("EmpresaID", "Codigo")
                        .IsUnique();

                    b.HasIndex("EmpresaID", "ListaDePrecioID");

                    b.HasIndex("EmpresaID", "TipoClienteID");

                    b.ToTable("Clientes", (string)null);
                });

            modelBuilder.Entity("WebMultiempresa.Domain.Entities.ClienteListaPrecios", b =>
                {
                    b.Property<int>("ClienteListasPreciosID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClienteListasPreciosID"));

                    b.Property<bool>("Baja")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("ClientesID")
                        .HasColumnType("int");

                    b.Property<int>("EmpresaID")
                        .HasColumnType("int");

                    b.Property<bool>("EsPrincipal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("ListasPreciosID")
                        .HasColumnType("int");

                    b.HasKey("ClienteListasPreciosID");

                    b.HasIndex("ListasPreciosID");

                    b.HasIndex("ClientesID", "ListasPreciosID")
                        .IsUnique();

                    b.ToTable("ClienteListasPrecios", (string)null);
                });

            modelBuilder.Entity("WebMultiempresa.Domain.Entities.ClienteVendedor", b =>
                {
                    b.Property<int>("ClienteVendedoresID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClienteVendedoresID"));

                    b.Property<bool>("Baja")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("ClientesID")
                        .HasColumnType("int");

                    b.Property<int>("EmpresaID")
                        .HasColumnType("int");

                    b.Property<int>("VendedoresID")
                        .HasColumnType("int");

                    b.HasKey("ClienteVendedoresID");

                    b.HasIndex("VendedoresID");

                    b.HasIndex("ClientesID", "VendedoresID")
                        .IsUnique();

                    b.ToTable("ClienteVendedores", (string)null);
                });

            modelBuilder.Entity("WebMultiempresa.Domain.Entities.Combo", b =>
                {
                    b.Property<int>("CombosID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CombosID"));

                    b.Property<bool>("Baja")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<decimal>("CantidadDinamica")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("CantidadDinamicaMaxima")
                        .HasColumnType("int");

                    b.Property<int>("CantidadFacturada")
                        .HasColumnType("int");

                    b.Property<decimal>("CantidadPorFactura")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CantidadSinCargo")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)")
                        .HasDefaultValue(1m);

                    b.Property<decimal>("CantidadXPDV")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<bool>("ClientesAlfaNumericos")
                        .HasColumnType("bit");

                    b.Property<bool>("ClientesNumericos")
                        .HasColumnType("bit");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("ComboDinamico")
                        .HasColumnType("bit");

                    b.Property<int?>("CupoTotal")
                        .HasColumnType("int");

                    b.Property<int>("EmpresaID")
                        .HasColumnType("int");

                    b.Property<bool>("EsDeIntroduccion")
                        .HasColumnType("bit");

                    b.Property<bool>("EsEstrategico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaVigencia")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("ImporteProductosFuera")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("ImpresionResumida")
                        .HasColumnType("bit");

                    b.Property<decimal>("MontoArrastre")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("NoImprimir")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("NombreAlternativo")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Nota")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PorcentajeComision")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("RubrosID")
                        .HasColumnType("int");

                    b.Property<bool>("SoloNoCompradores")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("SoloNoCompradoresDesde")
                        .HasColumnType("datetime2");

                    b.Property<bool>("TodasLasListasPrecios")
                        .HasColumnType("bit");

                    b.Property<bool>("TodasLasSucursales")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("TodosLosVendedores")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("TomaProdParaArrastre")
                        .HasColumnType("bit");

                    b.Property<bool>("UsarDescuentoClientes")
                        .HasColumnType("bit");

                    b.Property<bool>("ValidarPartido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("CombosID");

                    b.HasIndex("RubrosID");

                    b.HasIndex("EmpresaID", "Codigo")
                        .IsUnique();

                    b.ToTable("Combos", (string)null);
                });

            modelBuilder.Entity("WebMultiempresa.Domain.Entities.ComboFecha", b =>
                {
                    b.Property<int>("ComboFechasID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ComboFechasID"));

                    b.Property<int>("CombosID")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaFinal")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicial")
                        .HasColumnType("datetime2");

                    b.HasKey("ComboFechasID");

                    b.HasIndex("CombosID");

                    b.ToTable("ComboFechas", (string)null);
                });

            modelBuilder.Entity("WebMultiempresa.Domain.Entities.ComboItem", b =>
                {
                    b.Property<int>("ComboItemsID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ComboItemsID"));

                    b.Property<decimal>("Cantidad")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("CombosID")
                        .HasColumnType("int");

                    b.Property<decimal>("Descuento1")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("Descuento2")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("NroGrupoDinamico")
                        .HasColumnType("int");

                    b.Property<decimal>("Precio")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("ProductosID")
                        .HasColumnType("int");

                    b.Property<byte>("Tipo")
                        .HasColumnType("tinyint");

                    b.HasKey("ComboItemsID");

                    b.HasIndex("CombosID");

                    b.HasIndex("ProductosID");

                    b.ToTable("ComboItems", (string)null);
                });

            modelBuilder.Entity("WebMultiempresa.Domain.Entities.ComboListaPrecios", b =>
                {
                    b.Property<int>("ComboListaPreciosID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ComboListaPreciosID"));

                    b.Property<int>("CombosID")
                        .HasColumnType("int");

                    b.Property<int>("ListasPreciosID")
                        .HasColumnType("int");

                    b.HasKey("ComboListaPreciosID");

                    b.HasIndex("CombosID");

                    b.HasIndex("ListasPreciosID");

                    b.ToTable("ComboListasPrecios", (string)null);
                });

            modelBuilder.Entity("WebMultiempresa.Domain.Entities.ComboLog", b =>
                {
                    b.Property<int>("ComboLogsID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ComboLogsID"));

                    b.Property<int>("CombosID")
                        .HasColumnType("int");

                    b.Property<string>("Comentario")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("EmpresaID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("PC")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UsuariosID")
                        .HasColumnType("int");

                    b.HasKey("ComboLogsID");

                    b.HasIndex("CombosID");

                    b.ToTable("ComboLogs", (string)null);
                });

            modelBuilder.Entity("WebMultiempresa.Domain.Entities.ComboMarca", b =>
                {
                    b.Property<int>("ComboMarcasID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ComboMarcasID"));

                    b.Property<int>("CombosID")
                        .HasColumnType("int");

                    b.Property<int>("MarcasID")
                        .HasColumnType("int");

                    b.HasKey("ComboMarcasID");

                    b.HasIndex("MarcasID");

                    b.HasIndex("CombosID", "MarcasID")
                        .IsUnique();

                    b.ToTable("ComboMarcas", (string)null);
                });

            modelBuilder.Entity("WebMultiempresa.Domain.Entities.ComboRubro", b =>
                {
                    b.Property<int>("ComboRubrosID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ComboRubrosID"));

                    b.Property<int>("CombosID")
                        .HasColumnType("int");

                    b.Property<int>("RubrosID")
                        .HasColumnType("int");

                    b.HasKey("ComboRubrosID");

                    b.HasIndex("RubrosID");

                    b.HasIndex("CombosID", "RubrosID")
                        .IsUnique();

                    b.ToTable("ComboRubros", (string)null);
                });

            modelBuilder.Entity("WebMultiempresa.Domain.Entities.ComboSucursal", b =>
                {
                    b.Property<int>("ComboSucursalID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ComboSucursalID"));

                    b.Property<int>("CombosID")
                        .HasColumnType("int");

                    b.Property<int>("SucursalesID")
                        .HasColumnType("int");

                    b.HasKey("ComboSucursalID");

                    b.HasIndex("CombosID");

                    b.HasIndex("SucursalesID");

                    b.ToTable("ComboSucursales", (string)null);
                });

            modelBuilder.Entity("WebMultiempresa.Domain.Entities.ComboVendedor", b =>
                {
                    b.Property<int>("ComboVendedorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ComboVendedorID"));

                    b.Property<int>("CombosID")
                        .HasColumnType("int");

                    b.Property<int>("VendedoresID")
                        .HasColumnType("int");

                    b.HasKey("ComboVendedorID");

                    b.HasIndex("CombosID");

                    b.HasIndex("VendedoresID");

                    b.ToTable("ComboVendedores", (string)null);
                });

            modelBuilder.Entity("WebMultiempresa.Domain.Entities.Empresa", b =>
                {
                    b.Property<int>("EmpresaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmpresaID"));

                    b.Property<bool>("Baja")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("KeyConexion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("EmpresaID");

                    b.HasIndex("KeyConexion")
                        .IsUnique();

                    b.ToTable("Empresas", (string)null);
                });

            modelBuilder.Entity("WebMultiempresa.Domain.Entities.EmpresaAplicacion", b =>
                {
                    b.Property<int>("EmpresaAplicacionesID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmpresaAplicacionesID"));

                    b.Property<int>("AplicacionesID")
                        .HasColumnType("int");

                    b.Property<bool>("Baja")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("EmpresaID")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaActivacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaVencimiento")
                        .HasColumnType("datetime2");

                    b.HasKey("EmpresaAplicacionesID");

                    b.HasIndex("AplicacionesID");

                    b.HasIndex("EmpresaID", "AplicacionesID")
                        .IsUnique();

                    b.ToTable("EmpresaAplicaciones", (string)null);
                });

            modelBuilder.Entity("WebMultiempresa.Domain.Entities.EmpresaPlan", b =>
                {
                    b.Property<int>("EmpresaPlanesID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmpresaPlanesID"));

                    b.Property<bool>("Baja")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("EmpresaID")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaVencimiento")
                        .HasColumnType("datetime2");

                    b.Property<int>("PlanesID")
                        .HasColumnType("int");

                    b.HasKey("EmpresaPlanesID");

                    b.HasIndex("EmpresaID");

                    b.HasIndex("PlanesID");

                    b.ToTable("EmpresaPlanes", (string)null);
                });

            modelBuilder.Entity("WebMultiempresa.Domain.Entities.GpsPosicion", b =>
                {
                    b.Property<long>("GPS_PosicionesID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("GPS_PosicionesID"));

                    b.Property<int?>("AcuracyMetros")
                        .HasColumnType("int");

                    b.Property<int>("AplicacionesID")
                        .HasColumnType("int");

                    b.Property<decimal?>("DistanciaMetros")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("EmpresaID")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Latitud")
                        .HasColumnType("decimal(10,7)");

                    b.Property<decimal>("Longitud")
                        .HasColumnType("decimal(11,7)");

                    b.Property<string>("ModeloDispositivo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NumeroDispositivo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("OrigenEnvio")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("VelocidadKmh")
                        .HasColumnType("decimal(5,1)");

                    b.Property<int>("VendedoresID")
                        .HasColumnType("int");

                    b.HasKey("GPS_PosicionesID");

                    b.HasIndex("AplicacionesID");

                    b.HasIndex("VendedoresID");

                    b.HasIndex("EmpresaID", "VendedoresID", "FechaHora");

                    b.ToTable("GPS_Posiciones", (string)null);
                });

            modelBuilder.Entity("WebMultiempresa.Domain.Entities.ListaPrecios", b =>
                {
                    b.Property<int>("ListasPreciosID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ListasPreciosID"));

                    b.Property<bool>("Baja")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("EmpresaID")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ListasPreciosID");

                    b.HasIndex("EmpresaID");

                    b.ToTable("ListasPrecios", (string)null);
                });

            modelBuilder.Entity("WebMultiempresa.Domain.Entities.Marca", b =>
                {
                    b.Property<int>("MarcasID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MarcasID"));

                    b.Property<bool>("Baja")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("EmpresaID")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MarcasID");

                    b.HasIndex("EmpresaID");

                    b.ToTable("Marcas", (string)null);
                });

            modelBuilder.Entity("WebMultiempresa.Domain.Entities.Pedido", b =>
                {
                    b.Property<int>("PedidosID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PedidosID"));

                    b.Property<bool>("Baja")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("ClienteCodigo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ClienteDireccion")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("ClientesID")
                        .HasColumnType("int");

                    b.Property<string>("Comentario")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("ConsumidorFinal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("DeviceID")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Division")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("EmpresaID")
                        .HasColumnType("int");

                    b.Property<decimal>("EstadoArrastre")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<DateTime>("FechaCarga")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("FechaEntrega")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaTx")
                        .HasColumnType("datetime2");

                    b.Property<string>("KeyPagoID")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("Latitud")
                        .HasColumnType("decimal(18,10)");

                    b.Property<decimal?>("Longitud")
                        .HasColumnType("decimal(18,10)");

                    b.Property<string>("PaymentID")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("PedidoCerrado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("ResultadoTx")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte>("TipoCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)0);

                    b.Property<decimal>("TotalPedido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<int>("VendedoresID")
                        .HasColumnType("int");

                    b.HasKey("PedidosID");

                    b.HasIndex("EmpresaID", "ClientesID");

                    b.HasIndex("EmpresaID", "PedidoCerrado");

                    b.HasIndex("EmpresaID", "VendedoresID", "FechaCarga");

                    b.ToTable("Pedidos", (string)null);
                });

            modelBuilder.Entity("WebMultiempresa.Domain.Entities.PedidoDetalle", b =>
                {
                    b.Property<int>("PedidosDetalleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PedidosDetalleID"));

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(18,3)");

                    b.Property<int?>("CombosID")
                        .HasColumnType("int");

                    b.Property<decimal>("Descuento1")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(5,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("Descuento2")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(5,2)")
                        .HasDefaultValue(0m);

                    b.Property<bool>("EsCombo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int?>("GrupoDinamico")
                        .HasColumnType("int");

                    b.Property<int>("ListasPreciosID")
                        .HasColumnType("int");

                    b.Property<int>("PedidosID")
                        .HasColumnType("int");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("ProductosID")
                        .HasColumnType("int");

                    b.Property<byte?>("TipoComboItem")
                        .HasColumnType("tinyint");

                    b.Property<decimal?>("UnidadesPorBulto")
                        .HasColumnType("decimal(18,3)");

                    b.HasKey("PedidosDetalleID");

                    b.HasIndex("PedidosID");

                    b.ToTable("PedidosDetalle", (string)null);
                });

            modelBuilder.Entity("WebMultiempresa.Domain.Entities.Plan", b =>
                {
                    b.Property<int>("PlanesID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlanesID"));

                    b.Property<int>("AplicacionesID")
                        .HasColumnType("int");

                    b.Property<bool>("Baja")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("PlanesID");

                    b.HasIndex("AplicacionesID");

                    b.ToTable("Planes", (string)null);
                });

            modelBuilder.Entity("WebMultiempresa.Domain.Entities.PlanCapacidad", b =>
                {
                    b.Property<int>("PlanCapacidadesID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlanCapacidadesID"));

                    b.Property<int>("MaxCapacidad")
                        .HasColumnType("int");

                    b.Property<int>("PlanesID")
                        .HasColumnType("int");

                    b.Property<int>("TiposActoresID")
                        .HasColumnType("int");

                    b.HasKey("PlanCapacidadesID");

                    b.HasIndex("TiposActoresID");

                    b.HasIndex("PlanesID", "TiposActoresID")
                        .IsUnique();

                    b.ToTable("PlanCapacidades", (string)null);
                });

            modelBuilder.Entity("WebMultiempresa.Domain.Entities.Producto", b =>
                {
                    b.Property<int>("ProductosID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductosID"));

                    b.Property<bool>("Baja")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("EmpresaID")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("ProductosID");

                    b.HasIndex("EmpresaID");

                    b.ToTable("Productos", (string)null);
                });

            modelBuilder.Entity("WebMultiempresa.Domain.Entities.ProductoPrecio", b =>
                {
                    b.Property<int>("ProductoPreciosID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductoPreciosID"));

                    b.Property<bool>("Baja")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("EmpresaID")
                        .HasColumnType("int");

                    b.Property<int>("ListasPreciosID")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecioFinal")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("ProductosID")
                        .HasColumnType("int");

                    b.HasKey("ProductoPreciosID");

                    b.HasIndex("ListasPreciosID");

                    b.HasIndex("ProductosID", "ListasPreciosID")
                        .IsUnique();

                    b.ToTable("ProductoPrecios", (string)null);
                });

            modelBuilder.Entity("WebMultiempresa.Domain.Entities.Rubro", b =>
                {
                    b.Property<int>("RubrosID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RubrosID"));

                    b.Property<bool>("Baja")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("EmpresaID")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("RubrosID");

                    b.HasIndex("EmpresaID");

                    b.ToTable("Rubros", (string)null);
                });

            modelBuilder.Entity("WebMultiempresa.Domain.Entities.Sucursal", b =>
                {
                    b.Property<int>("SucursalesID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SucursalesID"));

                    b.Property<bool>("Baja")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("EmpresaID")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("SucursalesID");

                    b.HasIndex("EmpresaID");

                    b.ToTable("Sucursales", (string)null);
                });

            modelBuilder.Entity("WebMultiempresa.Domain.Entities.TipoActor", b =>
                {
                    b.Property<int>("TiposActoresID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TiposActoresID"));

                    b.Property<int>("AplicacionesID")
                        .HasColumnType("int");

                    b.Property<bool>("Baja")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("TiposActoresID");

                    b.HasIndex("AplicacionesID", "Codigo")
                        .IsUnique();

                    b.ToTable("TiposActores", (string)null);
                });

            modelBuilder.Entity("WebMultiempresa.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("UsuariosID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuariosID"));

                    b.Property<bool>("Baja")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("EmpresaID")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<byte>("Rol")
                        .HasColumnType("tinyint");

                    b.HasKey("UsuariosID");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("EmpresaID");

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("WebMultiempresa.Domain.Entities.UsuarioAppPermiso", b =>
                {
                    b.Property<int>("UsuarioAppPermisosID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioAppPermisosID"));

                    b.Property<int>("AplicacionesID")
                        .HasColumnType("int");

                    b.Property<bool>("Baja")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Permiso")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("UsuariosID")
                        .HasColumnType("int");

                    b.HasKey("UsuarioAppPermisosID");

                    b.HasIndex("AplicacionesID");

                    b.HasIndex("UsuariosID", "AplicacionesID", "Permiso")
                        .IsUnique();

                    b.ToTable("UsuarioAppPermisos", (string)null);
                });

            modelBuilder.Entity("WebMultiempresa.Domain.Entities.Vendedor", b =>
                {
                    b.Property<int>("VendedoresID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VendedoresID"));

                    b.Property<bool>("Baja")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("CantidadEstrellitas")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("ClaveHash")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("CoeficienteComision")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(10,4)")
                        .HasDefaultValue(0m);

                    b.Property<int>("EmpresaID")
                        .HasColumnType("int");

                    b.Property<string>("JsonDisponibles")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JsonEstrellas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("OcultarBotonEliminar")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("RutaDeVenta")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("TiposDeVendedoresID")
                        .HasColumnType("int");

                    b.Property<string>("UrlHomeVendedor")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("WhatsApp")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("VendedoresID");

                    b.HasIndex("EmpresaID", "Codigo")
                        .IsUnique();

                    b.ToTable("Vendedores", (string)null);
                });

            modelBuilder.Entity("WebMultiempresa.Domain.Entities.VendedorListaPrecios", b =>
                {
                    b.Property<int>("VendedorListasPreciosID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VendedorListasPreciosID"));

                    b.Property<bool>("Baja")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("EmpresaID")
                        .HasColumnType("int");

                    b.Property<bool>("EsDefault")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("ListasPreciosID")
                        .HasColumnType("int");

                    b.Property<int>("VendedoresID")
                        .HasColumnType("int");

                    b.HasKey("VendedorListasPreciosID");

                    b.HasIndex("ListasPreciosID");

                    b.HasIndex("VendedoresID");

                    b.ToTable("VendedorListasPrecios", (string)null);
                });

            modelBuilder.Entity("WebMultiempresa.Domain.Entities.ActorEstadoLog", b =>
                {
                    b.HasOne("WebMultiempresa.Domain.Entities.TipoActor", null)
                        .WithMany()
                        .HasForeignKey("TiposActoresID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("WebMultiempresa.Domain.Entities.AltaClientePendiente", b =>
                {
                    b.HasOne("WebMultiempresa.Domain.Entities.Empresa", null)
                        .WithMany()
                        .HasForeignKey("EmpresaID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("WebMultiempresa.Domain.Entities.Cliente", b =>
                {
                    b.HasOne("WebMultiempresa.Domain.Entities.Empresa", null)
                        .WithMany()
                        .HasForeignKey("EmpresaID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("WebMultiempresa.Domain.Entities.ClienteListaPrecios", b =>
                {
                    b.HasOne("WebMultiempresa.Domain.Entities.Cliente", null)
                        .WithMany()
                        .HasForeignKey("ClientesID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebMultiempresa.Domain.Entities.ListaPrecios", null)
                        .WithMany()
                        .HasForeignKey("ListasPreciosID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("WebMultiempresa.Domain.Entities.ClienteVendedor", b =>
                {
                    b.HasOne("WebMultiempresa.Domain.Entities.Cliente", null)
                        .WithMany()
                        .HasForeignKey("ClientesID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebMultiempresa.Domain.Entities.Vendedor", null)
                        .WithMany()
                        .HasForeignKey("VendedoresID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("WebMultiempresa.Domain.Entities.Combo", b =>
                {
                    b.HasOne("WebMultiempresa.Domain.Entities.Empresa", null)
                        .WithMany()
                        .HasForeignKey("EmpresaID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebMultiempresa.Domain.Entities.Rubro", "Rubro")
                        .WithMany()
                        .HasForeignKey("RubrosID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rubro");
                });

            modelBuilder.Entity("WebMultiempresa.Domain.Entities.ComboFecha", b =>
                {
                    b.HasOne("WebMultiempresa.Domain.Entities.Combo", null)
                        .WithMany("Fechas")
                        .HasForeignKey("CombosID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WebMultiempresa.Domain.Entities.ComboItem", b =>
                {
                    b.HasOne("WebMultiempresa.Domain.Entities.Combo", null)
                        .WithMany("Items")
                        .HasForeignKey("CombosID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebMultiempresa.Domain.Entities.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductosID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("WebMultiempresa.Domain.Entities.ComboListaPrecios", b =>
                {
                    b.HasOne("WebMultiempresa.Domain.Entities.Combo", null)
                        .WithMany("ListasPrecios")
                        .HasForeignKey("CombosID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebMultiempresa.Domain.Entities.ListaPrecios", null)
                        .WithMany()
                        .HasForeignKey("ListasPreciosID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("WebMultiempresa.Domain.Entities.ComboLog", b =>
                {
                    b.HasOne("WebMultiempresa.Domain.Entities.Combo", null)
                        .WithMany("Logs")
                        .HasForeignKey("CombosID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WebMultiempresa.Domain.Entities.ComboMarca", b =>
                {
                    b.HasOne("WebMultiempresa.Domain.Entities.Combo", null)
                        .WithMany("MarcasArrastre")
                        .HasForeignKey("CombosID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebMultiempresa.Domain.Entities.Marca", "Marca")
                        .WithMany()
                        .HasForeignKey("MarcasID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Marca");
                });

            modelBuilder.Entity("WebMultiempresa.Domain.Entities.ComboRubro", b =>
                {
                    b.HasOne("WebMultiempresa.Domain.Entities.Combo", null)
                        .WithMany("RubrosArrastre")
                        .HasForeignKey("CombosID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebMultiempresa.Domain.Entities.Rubro", "Rubro")
                        .WithMany()
                        .HasForeignKey("RubrosID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rubro");
                });

            modelBuilder.Entity("WebMultiempresa.Domain.Entities.ComboSucursal", b =>
                {
                    b.HasOne("WebMultiempresa.Domain.Entities.Combo", null)
                        .WithMany("Sucursales")
                        .HasForeignKey("CombosID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebMultiempresa.Domain.Entities.Sucursal", null)
                        .WithMany()
                        .HasForeignKey("SucursalesID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("WebMultiempresa.Domain.Entities.ComboVendedor", b =>
                {
                    b.HasOne("WebMultiempresa.Domain.Entities.Combo", null)
                        .WithMany("Vendedores")
                        .HasForeignKey("CombosID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebMultiempresa.Domain.Entities.Vendedor", null)
                        .WithMany()
                        .HasForeignKey("VendedoresID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("WebMultiempresa.Domain.Entities.EmpresaAplicacion", b =>
                {
                    b.HasOne("WebMultiempresa.Domain.Entities.Aplicacion", null)
                        .WithMany()
                        .HasForeignKey("AplicacionesID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebMultiempresa.Domain.Entities.Empresa", null)
                        .WithMany()
                        .HasForeignKey("EmpresaID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("WebMultiempresa.Domain.Entities.EmpresaPlan", b =>
                {
                    b.HasOne("WebMultiempresa.Domain.Entities.Empresa", null)
                        .WithMany()
                        .HasForeignKey("EmpresaID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebMultiempresa.Domain.Entities.Plan", null)
                        .WithMany()
                        .HasForeignKey("PlanesID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("WebMultiempresa.Domain.Entities.GpsPosicion", b =>
                {
                    b.HasOne("WebMultiempresa.Domain.Entities.Aplicacion", null)
                        .WithMany()
                        .HasForeignKey("AplicacionesID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebMultiempresa.Domain.Entities.Vendedor", null)
                        .WithMany()
                        .HasForeignKey("VendedoresID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("WebMultiempresa.Domain.Entities.ListaPrecios", b =>
                {
                    b.HasOne("WebMultiempresa.Domain.Entities.Empresa", null)
                        .WithMany()
                        .HasForeignKey("EmpresaID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("WebMultiempresa.Domain.Entities.Marca", b =>
                {
                    b.HasOne("WebMultiempresa.Domain.Entities.Empresa", null)
                        .WithMany()
                        .HasForeignKey("EmpresaID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("WebMultiempresa.Domain.Entities.Pedido", b =>
                {
                    b.HasOne("WebMultiempresa.Domain.Entities.Empresa", null)
                        .WithMany()
                        .HasForeignKey("EmpresaID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("WebMultiempresa.Domain.Entities.PedidoDetalle", b =>
                {
                    b.HasOne("WebMultiempresa.Domain.Entities.Pedido", null)
                        .WithMany()
                        .HasForeignKey("PedidosID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WebMultiempresa.Domain.Entities.Plan", b =>
                {
                    b.HasOne("WebMultiempresa.Domain.Entities.Aplicacion", null)
                        .WithMany()
                        .HasForeignKey("AplicacionesID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("WebMultiempresa.Domain.Entities.PlanCapacidad", b =>
                {
                    b.HasOne("WebMultiempresa.Domain.Entities.Plan", null)
                        .WithMany()
                        .HasForeignKey("PlanesID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebMultiempresa.Domain.Entities.TipoActor", null)
                        .WithMany()
                        .HasForeignKey("TiposActoresID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("WebMultiempresa.Domain.Entities.Producto", b =>
                {
                    b.HasOne("WebMultiempresa.Domain.Entities.Empresa", null)
                        .WithMany()
                        .HasForeignKey("EmpresaID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("WebMultiempresa.Domain.Entities.ProductoPrecio", b =>
                {
                    b.HasOne("WebMultiempresa.Domain.Entities.ListaPrecios", null)
                        .WithMany()
                        .HasForeignKey("ListasPreciosID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebMultiempresa.Domain.Entities.Producto", null)
                        .WithMany()
                        .HasForeignKey("ProductosID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("WebMultiempresa.Domain.Entities.Rubro", b =>
                {
                    b.HasOne("WebMultiempresa.Domain.Entities.Empresa", null)
                        .WithMany()
                        .HasForeignKey("EmpresaID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("WebMultiempresa.Domain.Entities.Sucursal", b =>
                {
                    b.HasOne("WebMultiempresa.Domain.Entities.Empresa", null)
                        .WithMany()
                        .HasForeignKey("EmpresaID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("WebMultiempresa.Domain.Entities.TipoActor", b =>
                {
                    b.HasOne("WebMultiempresa.Domain.Entities.Aplicacion", null)
                        .WithMany()
                        .HasForeignKey("AplicacionesID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("WebMultiempresa.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("WebMultiempresa.Domain.Entities.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaID");

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("WebMultiempresa.Domain.Entities.UsuarioAppPermiso", b =>
                {
                    b.HasOne("WebMultiempresa.Domain.Entities.Aplicacion", null)
                        .WithMany()
                        .HasForeignKey("AplicacionesID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebMultiempresa.Domain.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuariosID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WebMultiempresa.Domain.Entities.Vendedor", b =>
                {
                    b.HasOne("WebMultiempresa.Domain.Entities.Empresa", null)
                        .WithMany()
                        .HasForeignKey("EmpresaID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("WebMultiempresa.Domain.Entities.VendedorListaPrecios", b =>
                {
                    b.HasOne("WebMultiempresa.Domain.Entities.ListaPrecios", null)
                        .WithMany()
                        .HasForeignKey("ListasPreciosID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebMultiempresa.Domain.Entities.Vendedor", null)
                        .WithMany()
                        .HasForeignKey("VendedoresID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("WebMultiempresa.Domain.Entities.Combo", b =>
                {
                    b.Navigation("Fechas");

                    b.Navigation("Items");

                    b.Navigation("ListasPrecios");

                    b.Navigation("Logs");

                    b.Navigation("MarcasArrastre");

                    b.Navigation("RubrosArrastre");

                    b.Navigation("Sucursales");

                    b.Navigation("Vendedores");
                });
#pragma warning restore 612, 618
        }
    }
}
